### ISSUE TITLE
[Q] Pod can specify GPU device-id?

### ISSUE THREAD

**Issue by sakaia** [RadeonOpenCompute/k8s-device-plugin#10]
Pod can specify GPU device-id for 1-node multi GPU case.
If it is available, Would you show me a document? 

P.S.
I am just watching following Reference document. And I realized device-id in label.

Ref 
https://github.com/RadeonOpenCompute/k8s-device-plugin/blob/master/cmd/k8s-node-labeller/README.md

**Comment by y2kenny** [comment]
The labeller can label with device-id and you can assign pod by label.  But, unfortunately, when a GPU device is assigned to the pod, the device ID is not in the request so the scheduling wouldn't work if you have GPUs of different device ID on the same node.
