### ISSUE TITLE
would all pods using the same GPU are assigned to the same NUMA?

### ISSUE THREAD

**Issue by mrpre** [RadeonOpenCompute/k8s-device-plugin#20]
I found the `ListAndWatch` gives the NUMA attribute to GPU
https://github.com/RadeonOpenCompute/k8s-device-plugin/blob/78322e52930b2d4925dbd796c86a3519c45e4bfe/cmd/k8s-device-plugin/main.go#L148-L165

But in `Allocate ` I can't find such assignment.  
So what  does  NUMA logic in `ListAndWatch` use for ?   I'm confused the relation between the `pluginapi.Device` and `pluginapi.DeviceSpec` .
And is it reasonable that the POD and the GPU should exist in same NUMA node?

**Comment by y2kenny** [comment]
I think the coordination is done by the Topology Manager at the cluster level:
https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/
