### ISSUE TITLE
Not Working On Ubuntu 20.04 Kernel 5.8 HWE

### ISSUE THREAD

**Issue by sstubbs** [RadeonOpenCompute/k8s-device-plugin#21]
Hi,

I am very interested in this however I cannot get it to work. I've tried 4 different driver/kernel options which are:
- AMD 21.10 open driver
- AMD 21.10 pro driver
- Rocm 4.2 installed with rocm-dkms package
- Rocm 4.2 installed with rocm-dev and rocm-utils packages

With rocm both:
/opt/rocm/bin/rocminfo
/opt/rocm/opencl/bin/clinfo
are showing the vega 64 card correctly however when I run this plugin on Kubernetes I am getting the following error:
```
I0708 02:16:43.300491 1 manager.go:71] Received new list of plugins: [gpu]
I0708 02:16:43.300587 1 manager.go:110] Adding a new plugin "gpu"
I0708 02:16:43.300602 1 plugin.go:64] gpu: Starting plugin server
I0708 02:16:43.300606 1 plugin.go:95] gpu: Starting the DPI gRPC server
I0708 02:16:43.300852 1 plugin.go:113] gpu: Serving requests...
I0708 02:16:53.301785 1 plugin.go:129] gpu: Registering the DPI with Kubelet
I0708 02:16:53.302111 1 plugin.go:141] gpu: Registration for endpoint amd.com_gpu
I0708 02:16:53.304758 1 amdgpu.go:100] /sys/module/amdgpu/drivers/pci:amdgpu/0000:28:00.0
I0708 02:16:53.334427 1 main.go:149] Watching GPU with bus ID: 0000:28:00.0 NUMA Node: []
E0708 02:16:53.334443 1 main.go:151] No NUMA node found with bus ID: 0000:28:00.0
```
I am using this GPU for my display and I was hoping I could share it with my local Kubernetes installation but it doesn't seem to be working.

The bus ID it is finding is correct but I'm wondering is there something else I should install to enable the numa node? numactl is not finding this gpu either but I'm not sure if it should with AMD GPUs.

**Comment by sstubbs** [comment]
I have just seen this issue https://github.com/RadeonOpenCompute/k8s-device-plugin/issues/11 so I guess the Vega 64 is not supported. Is there a list of compatible cards for this? I assumed it would be the same as Rocm.

**Comment by y2kenny** [comment]
What does your `kubectl describe node <gpu node>` looks like?

**Comment by sunway513** [comment]
According to the official ROCm document, 5.8 base kernel driver is not supported by ROCm4.2:
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#prerequisites
