### ISSUE TITLE
Registration failing on K3s

### ISSUE THREAD

**Issue by Scrumplex** [RadeonOpenCompute/k8s-device-plugin#31]
When starting the amd-gpu DaemonSet (From Helm Chart `amd-gpu-0.5.0`, running the image `docker.io/rocm/k8s-device-plugin:1.25.2`)
I can see these errors in its log:
```
I1125 09:01:30.600494       1 plugin.go:64] gpu: Starting plugin server
I1125 09:01:30.600565       1 plugin.go:127] gpu: Registering the DPI with Kubelet
I1125 09:01:30.601778       1 plugin.go:139] gpu: Registration for endpoint amd.com_gpu
E1125 09:01:40.606674       1 plugin.go:156] gpu: Registration failed: rpc error: code = Unknown desc = failed to dial device plugin: context deadline exceeded
E1125 09:01:40.606782       1 plugin.go:157] gpu: Make sure that the DevicePlugins feature gate is enabled and kubelet running
E1125 09:01:40.607097       1 plugin.go:78] error registering with device plugin manager: rpc error: code = Unknown desc = failed to dial device plugin: context deadline exceeded
E1125 09:01:40.607154       1 manager.go:214] Failed to start plugin's "gpu" server, atempt 2 ouf of 3 waiting 3000000000 before next try: rpc error: code = Unknown desc = failed to dial device plugin: context deadline exceeded
```

And at the same time, these errors in the K3s service log:
```
I1125 10:01:30.604506  143363 server.go:142] "Got registration request from device plugin with resource" resourceName="amd.com/gpu"
E1125 10:01:40.605838  143363 client.go:65] "Unable to connect to device plugin client with socket path" err="failed to dial device plugin: context deadline exceeded" path="/var/lib/kubelet/device-plugins/amd.com_gpu"
E1125 10:01:40.605952  143363 handler.go:73] "Failed to connect to new client" err="failed to dial device plugin: context deadline exceeded" resource="amd.com/gpu"
I1125 10:01:40.606075  143363 server.go:158] "Error connecting to device plugin client" err="failed to dial device plugin: context deadline exceeded"
```

k3s version v1.25.3+k3s1 (f2585c16)
go version go1.19.3

**Comment by Scrumplex** [comment]
I have tried [Intel's GPU plugin](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/gpu_plugin/README.md) as well and it worked without a hitch.

**Comment by y2kenny** [comment]
what is the Linux distribution you are using and what is the ROCm version you have installed?

**Comment by Scrumplex** [comment]
I am using NixOS 22.11 and I actually don't have any ROCm components installed. I only have a recent kernel with the amdgpu driver. I was only planning to make use of the hardware video encoding capabilities of the GPU

**Comment by hippotread** [comment]
Hi - I'm having the same issues with gpu registering in a k3s container.

Debian 11
AMD Ryzen 5 5600G
Kernel: 5.15.62+truenas
k3s version v1.25.3+k3s-34572b61-dirty (34572b61)
go version go1.19.1
rocm 5.4.0

Output of rocminfo:
`ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 5 5600G with Radeon Graphics
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 5 5600G with Radeon Graphics
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3900                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            12                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    65132524(0x3e1d7ec) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    65132524(0x3e1d7ec) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65132524(0x3e1d7ec) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx90c                             
  Uuid:                    GPU-XX                             
  Marketing Name:                                             
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      1024(0x400) KB                     
  Chip ID:                 5688(0x1638)                       
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1900                               
  BDFID:                   2048                               
  Internal Node ID:        1                                  
  Compute Unit:            7                                  
  SIMDs per CU:            4                                  
  Shader Engines:          1                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    524288(0x80000) KB                 
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx90c:xnack+   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***       `

Using amdgpu driver but unsure of version if that matters:
` *-display                 
       description: VGA compatible controller
       product: Cezanne
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:08:00.0
       version: c9
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi msix vga_controller bus_master cap_list
       configuration: driver=amdgpu latency=0
       resources: iomemory:7f0-7ef iomemory:7f0-7ef irq:29 memory:7fe0000000-7fefffffff memory:7ff0000000-7ff01fffff ioport:e000(size=256) memory:fce00000-fce7ffff
`

**Comment by hippotread** [comment]
After a bit of troubleshooting, I found out this issue does not occur in the 1.18.0 docker image. 
```
I1221 09:18:08.315406       1 main.go:296] AMD GPU device plugin for Kubernetes
I1221 09:18:08.315456       1 main.go:296] ./k8s-device-plugin version v1.18-0-g3775549
I1221 09:18:08.315460       1 main.go:296] hwloc: _VERSION: 2.2.0, _API_VERSION: 0x00020100, _COMPONENT_ABI: 6, Runtime: 0x00020100
I1221 09:18:08.315469       1 manager.go:42] Starting device plugin manager
I1221 09:18:08.315474       1 manager.go:46] Registering for system signal notifications
I1221 09:18:08.315723       1 manager.go:52] Registering for notifications of filesystem changes in device plugin directory
I1221 09:18:08.315845       1 manager.go:60] Starting Discovery on new plugins
I1221 09:18:08.315856       1 manager.go:66] Handling incoming signals
I1221 09:18:08.315877       1 manager.go:71] Received new list of plugins: [gpu]
I1221 09:18:08.315970       1 manager.go:110] Adding a new plugin "gpu"
I1221 09:18:08.315988       1 plugin.go:64] gpu: Starting plugin server
I1221 09:18:08.315993       1 plugin.go:95] gpu: Starting the DPI gRPC server
I1221 09:18:08.316241       1 plugin.go:113] gpu: Serving requests...
I1221 09:18:18.317854       1 plugin.go:129] gpu: Registering the DPI with Kubelet
I1221 09:18:18.318096       1 plugin.go:141] gpu: Registration for endpoint amd.com_gpu
I1221 09:18:18.321137       1 amdgpu.go:100] /sys/module/amdgpu/drivers/pci:amdgpu/0000:08:00.0
I1221 09:18:18.345696       1 main.go:149] Watching GPU with bus ID: 0000:08:00.0 NUMA Node: []
E1221 09:18:18.345711       1 main.go:151] No NUMA node found with bus ID: 0000:08:00.0

```

**Comment by Scrumplex** [comment]
> After a bit of troubleshooting, I found out this issue does not occur in the 1.18.0 docker image.
> 
> ```
> I1221 09:18:08.315406       1 main.go:296] AMD GPU device plugin for Kubernetes
> I1221 09:18:08.315456       1 main.go:296] ./k8s-device-plugin version v1.18-0-g3775549
> I1221 09:18:08.315460       1 main.go:296] hwloc: _VERSION: 2.2.0, _API_VERSION: 0x00020100, _COMPONENT_ABI: 6, Runtime: 0x00020100
> I1221 09:18:08.315469       1 manager.go:42] Starting device plugin manager
> I1221 09:18:08.315474       1 manager.go:46] Registering for system signal notifications
> I1221 09:18:08.315723       1 manager.go:52] Registering for notifications of filesystem changes in device plugin directory
> I1221 09:18:08.315845       1 manager.go:60] Starting Discovery on new plugins
> I1221 09:18:08.315856       1 manager.go:66] Handling incoming signals
> I1221 09:18:08.315877       1 manager.go:71] Received new list of plugins: [gpu]
> I1221 09:18:08.315970       1 manager.go:110] Adding a new plugin "gpu"
> I1221 09:18:08.315988       1 plugin.go:64] gpu: Starting plugin server
> I1221 09:18:08.315993       1 plugin.go:95] gpu: Starting the DPI gRPC server
> I1221 09:18:08.316241       1 plugin.go:113] gpu: Serving requests...
> I1221 09:18:18.317854       1 plugin.go:129] gpu: Registering the DPI with Kubelet
> I1221 09:18:18.318096       1 plugin.go:141] gpu: Registration for endpoint amd.com_gpu
> I1221 09:18:18.321137       1 amdgpu.go:100] /sys/module/amdgpu/drivers/pci:amdgpu/0000:08:00.0
> I1221 09:18:18.345696       1 main.go:149] Watching GPU with bus ID: 0000:08:00.0 NUMA Node: []
> E1221 09:18:18.345711       1 main.go:151] No NUMA node found with bus ID: 0000:08:00.0
> ```

Can confirm. I might try to bisect this bug.

**Comment by rotilho** [comment]
Same here. Downgrade to 1.18 works.

**Comment by agilob** [comment]
Anyone here found an alternative solution?

**Comment by SISheogorath** [comment]
This seems to be related to the Kubernetes version. The problem appeared today when upgrading from Kubernetes 1.24.11 to 1.25.8. (Nothing else was adjusted, no OS packages, not kernel, no reboot)

Interestingly enough, forcing the downgrade, [as suggested by @rotilho](https://github.com/RadeonOpenCompute/k8s-device-plugin/issues/31#issuecomment-1374533510), makes it work again.

**Comment by SISheogorath** [comment]
With some investigation, this seems to originate from a bug in the device-plugin library used by this setup:

This PR should have resolved it upstream and is the only change for version 1.19.4:
https://github.com/kubevirt/device-plugin-manager/pull/21

https://github.com/kubevirt/device-plugin-manager/releases/tag/v1.19.4

https://github.com/RadeonOpenCompute/k8s-device-plugin/blob/d4b18541a7d956cb167a2949ed98d00fd3cad187/go.mod#L8

**Comment by y2kenny** [comment]
Thanks for the investigation.  I will make an update shortly.

**Comment by sfxworks** [comment]
I am running into this issue on arch...
