### ISSUE TITLE
Deprecated k8s apiversion in yaml

### ISSUE THREAD

**Issue by abuccts** [RadeonOpenCompute/k8s-device-plugin#7]
`extensions/v1beta1` is deprecated for DaemonSet in Kuberentes v1.16
https://github.com/RadeonOpenCompute/k8s-device-plugin/blob/661b5788a9362cfc05e7f82a1293caee9a2b6997/k8s-ds-amdgpu-dp.yaml#L1
https://github.com/RadeonOpenCompute/k8s-device-plugin/blob/661b5788a9362cfc05e7f82a1293caee9a2b6997/k8s-ds-amdgpu-dp-health.yaml#L7

better change to `apps/v1`, which is available since v1.9.

reference: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by y2kenny** [comment]
Thanks for spotting the API change!
