### ISSUE TITLE
Is it possible to restrict vram/cu per pod?

### ISSUE THREAD

**Issue by hyc3z** [RadeonOpenCompute/k8s-device-plugin#9]
Is there a possible way to limit the rescources used by a pod/ container?
For example, we have a Radeon Vii card which has 16G vram.
Is it possible that one pod is limited to use 4GB vram, another is limited to use 6GB vram, and the rest 6G is available for pod scheduling?

**Comment by y2kenny** [comment]
This is not currently possible.  I have a proposal up in the linux kernel mailing list to have something like this supported natively in cgroup but that feature is very far from being accepted at this point.

**Comment by elukey** [comment]
@y2kenny Hi! Has anything changed by any chance? I am wondering if in the future we may be able to share a single GPUs between multiple containers (Nvidia offers some options but they are heavily CUDA based, the approach that you mentioned seemed way more generic and robust but I didn't find any state of it in the LKML). Thanks in advance!
